export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_FAIL = "LOGIN_ADMIN_FAIL";
export const TOKEN_VALIDATION = "TOKEN_VALIDATION";
export const TOKEN_VALIDATION_SUCCESS = "TOKEN_VALIDATION_SUCCESS";
export const TOKEN_VALIDATION_FAIL = "TOKEN_VALIDATION_FAIL";
export const LOGOUT_ADMIN = "LOGOUT_ADMIN";